# docker-compose.yml
version: "3.8"
services:
  whisper-service:
    build:
      context: ./whisper-service
    ports:
      - "5001:5001"
    volumes:
      - ./whisper-service/uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - feedback-service

  feedback-service:
    build:
      context: ./feedback-service
    ports:
      - "5002:5002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
